title: "Transformer-Based Deep Learning for Protein Function Prediction"
description: "Experiments from the CAFA-6 Challenge"
theme: jekyll-theme-minimal
show_downloads: false
github:
  is_project_page: false
